### ISSUE TITLE
ge method of SortedSet only returns greater than, not greater than or equal to

### ISSUE THREAD

**Issue by luipugs** [kiddouk/redisco#23]
In the ge method of SortedSet in containers.py, the score for the min should not have an open parenthesis. With the open parenthesis it becomes an open interval, as described in the documentation for redis: http://redis.io/commands/zrangebyscore.

**Comment by stuaxo** [comment]
Looks like the implementation has been changed, so maybe this has been fixed?

**Comment by kiddouk** [comment]
yes, this has been fixed in 2e74152f8989ce26d0d5ae95d79b409a1698b7a2
