### ISSUE TITLE
How to run rediscos tests?

### ISSUE THREAD

**Issue by stuaxo** [kiddouk/redisco#49]
Hi,
   How do I run rediscos tests, on python 3.5 ?

I tried ```python setup.py test``` but that didn't work ?

I want to add a feature, but need to make sure I don't break anything ?

Cheers
S

**Comment by stuaxo** [comment]
OK, I saw these run by using ```nosetests``` I'll try and make ```python setup.py test``` do something useful.

**Comment by kiddouk** [comment]
Thanks for this.. Will review and close this issue. 🙌
